In [ ]:
for i, x in enumerate(['A', 'B', 'C']):
    print(i, x)

0 A
1 B
2 C


In [ ]:
# For loop example

dates = [1982,1980,1973]
N = len(dates)

for i in range(N):
    print(dates[i])  

1982
1980
1973


In [ ]:
# Example of for loop

for i in range(0, 8):
    print(i)

0
1
2
3
4
5
6
7


In [ ]:
print(help(len))

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.

None


In [ ]:
def factorial(n):
    if n == 0:
        return 1
    else:
        return n * factorial(n-1)

print(factorial(5))

120


In [ ]:
def calculate_total(a, b):  # Parameters: a and b
    total = a + b           # Task: Addition
    return total            # Output: Sum of a and b
result = calculate_total(5, 7)  # Calling the function with inputs 5 and 7
print(result)  # Output: 12

12


In [ ]:
string_length = len("Hello, World!")  # Output: 13
list_length = len([1, 2, 3, 4, 5])   # Output: 5
list_length

5

In [ ]:

total = sum([10, 20, 30, 40, 50])  # Output: 150
total

150

In [ ]:

lowest = min([5, 12, 8, 23, 16])  # Output: 5
lowest

5

In [ ]:
highest = max([5, 12, 8, 23, 16])  # Output: 23
highest

23

In [ ]:
def function_name():
    pass  # Placeholder for future code

In [ ]:
def greet(name):
    return "Hello, " + name
result = greet("Youssef")
print(result)  # Output: Hello, Youssef

Hello, Youssef


In [ ]:
def multiply(a, b):
    """
    This function multiplies two numbers.
    Input: a (number), b (number)
    Output: Product of a and b
    """
    return a * b
result = multiply(2, 6)
print(result)  # Output: 12

12


In [ ]:
def add(a, b):
    return a + b
sum_result = add(3, 5)  # sum_result gets the value 8
print(sum_result)  # Output: 8

8


In [ ]:
global_variable = "I'm global"

def example_function():
    local_variable = "I'm local"
    print(global_variable)  # Accessing global variable
    print(local_variable)   # Accessing local variable
    
example_function()

I'm global
I'm local


In [ ]:
def print_numbers(limit):
    for i in range(1, limit+1):
        print(i)
print_numbers(5)  # Output: 1 2 3 4 5

1
2
3
4
5


In [ ]:
def greet(name):
    return "Hello, " + name
for _ in range(3):
    print(greet("Youssef"))

Hello, Youssef
Hello, Youssef
Hello, Youssef


In [ ]:
# Define an empty list as the initial data structure
my_list = []
# Function to add an element to the list
def add_element(data_structure, element):
    data_structure.append(element)

def remove_element(data_structure, element):
    if element in data_structure:
        data_structure.remove(element)
    else:
        print(f"{element} not found in the list.")
        
# Add elements to the list using the add_element function
add_element(my_list, 42)
add_element(my_list, 17)
add_element(my_list, 99)

In [ ]:
# Print the current list
print("Current list:", my_list)

Current list: [42, 17, 99]


In [ ]:
# Remove an element from the list using the remove_element function
remove_element(my_list, 17)
remove_element(my_list, 55)  # This will print a message since 55 is not in the list
print("Updated list:", my_list)

17 not found in the list.
55 not found in the list.
Updated list: [42, 99]


In [ ]:
len(['A','B',1])

3

In [ ]:
len([sum([1,1,1])])

1

In [ ]:
L=[1,3,2]

sorted(L) 
print(L)

[1, 3, 2]


In [ ]:
def print_function(A):
    for a in A:
        print(a + '1')
print_function(['a', 'b', 'c'])

a1
b1
c1


In [ ]:
#result = 10 / 0 
#print(result)
# using Try- except 
try:
    # Attempting to divide 10 by 0
    result = 10 / 0
except ZeroDivisionError:
    # Handling the ZeroDivisionError and printing an error message
    print("Error: Cannot divide by zero")
# This line will be executed regardless of whether an exception occurred
print("outside of try and except block")

Error: Cannot divide by zero
outside of try and except block


In [ ]:
#with open("nonexistent_file.txt", "r") as file:
#        content = file.read()   # Raises FileNotFoundError
        
# using Try- except 
try:
    with open("nonexistent_file.txt", "r") as file:
        content = file.read()   # Raises FileNotFoundError
except FileNotFoundError:
    # Handling the FileNotFoundError and printing an error message
    print("Error: File Not Found Error")
# This line will be executed regardless of whether an exception occurred
print("outside of try and except block")

Error: File Not Found Error
outside of try and except block


In [ ]:
my_list = [1, 2, 3]
value = my_list[1]  # No IndexError, within range
missing = my_list[5]  # Raises IndexError

IndexError: list index out of range

In [ ]:
my_dict = {"name": "Alice", "age": 30}
value = my_dict.get("city")  # No KeyError, using .get() method
missing = my_dict["city"]  # Raises KeyError

KeyError: 'city'

In [ ]:

result = "hello" + 5   
# Raises TypeError

TypeError: can only concatenate str (not "int") to str

In [ ]:
text = "example"
length = len(text)  # No AttributeError, correct method usage
missing = text.some_method()  # Raises AttributeError

AttributeError: 'str' object has no attribute 'some_method'

In [ ]:
class Car:
    # Class attribute (shared by all instances)
    max_speed = 120  # Maximum speed in km/h
    # Constructor method (initialize instance attributes)
    def __init__(self, make, model, color, speed=0):
        self.make = make
        self.model = model
        self.color = color
        self.speed = speed  # Initial speed is set to 0
    # Method for accelerating the car
    def accelerate(self, acceleration):
        if self.speed + acceleration <= Car.max_speed:
            self.speed += acceleration
        else:
            self.speed = Car.max_speed
    # Method to get the current speed of the car
    def get_speed(self):
        return self.speed

In [ ]:
# Create objects (instances) of the Car class
car1 = Car("Toyota", "Camry", "Blue")
car2 = Car("Honda", "Civic", "Red")

# Accelerate the cars
car1.accelerate(30)
car2.accelerate(20)

# Print the current speeds of the cars
print(f"{car1.make} {car1.model} is currently at {car1.get_speed()} km/h.")
print(f"{car2.make} {car2.model} is currently at {car2.get_speed()} km/h.")

Toyota Camry is currently at 30 km/h.
Honda Civic is currently at 20 km/h.


In [ ]:
class Circle(object):
    # Constructor
    def __init__(self, radius=3, color='blue'):
        self.radius = radius
        self.color = color
        
    # Method
    def add_radius(self, r):
        self.radius = self.radius + r
        return self.radius
    
CircleObject = Circle()

CircleObject.radius = 10
print(CircleObject.radius, CircleObject.color)

10 blue


In [ ]:
class Circle(object):
    # Constructor
    def __init__(self, radius=3, color='blue'):
        self.radius = radius
        self.color = color


    # Method
    def add_radius(self, r):
        self.radius = self.radius + r
        return self.radius
    
c1 = Circle(4, 'yellow')
print(c1.radius, c1.color)  # Output: 4 yellow

4 yellow


In [ ]:
class Vehicle:
    color = "white"


    def __init__(self, max_speed, mileage):
        self.max_speed = max_speed
        self.mileage = mileage
        self.seating_capacity = None


    def assign_seating_capacity(self, seating_capacity):
        self.seating_capacity = seating_capacity


V1 = Vehicle(150, 25)
print(V1.color, V1.max_speed, V1.mileage)  # Output: white 150 25

white 150 25


In [ ]:
class Graph():
    def __init__(self, id):
        self.id = id
        self.id = 80


val = Graph(200)
print(val.id)

80


In [ ]:
signal_state = "Red"
if signal_state == "Green":
    print("Walk")
else:
    print("Wait")
print("Look both ways")

Wait
Look both ways


In [ ]:
x = 1 
x = x > 5
x

False

In [ ]:
x = 5 
while x != 2: 
    print(x) 
    x = x - 1

5
4
3


In [ ]:
class Coordinate(object):
    def __init__(self, x, y):
        self.x = x
        self.y = y
    def display(self):
        print(f"Position: ({self.x}, {self.y})")
cursor = Coordinate(15, 30)
cursor.display()

Position: (15, 30)


In [ ]:
for i, x in enumerate(['A', 'B', 'C']):
    print(i, 2 * x)

0 AA
1 BB
2 CC


In [ ]:
class WeatherData:
    def __init__(self, temp_c, humidity):
        self.temp_c = temp_c
        self.humidity = humidity
    def display(self):
        print(f"Temperature: {self.temp_c}°C, Humidity: {self.humidity}%")
today = WeatherData(22, 45)
today.temp_c = 25
today.display()

Temperature: 25°C, Humidity: 45%


In [ ]:
def delta(x): 
    if x == 0: 
        y = 1 
    else: 
        y = 0 
    return y

print(delta(0))

1


In [1]:
a = 1 
def do(x): 
    a = 100 
    return x + a 
print(do(1))

101


In [5]:
with open("data.txt", "r") as file: 
    content = file.read() 
    print(content) 
with open("output.txt", "w") as file: 
    file.write("Hello, world!") 
with open("log.txt", "a") as file: 
    file.write("Log entry: Something happened.") 
with open("data.txt", "r+") as file: 
    content = file.read() 
    file.write(" Updated content: " + content)

data in the file


In [9]:
with open("data.txt", "r") as file:
    # lines = file.readlines()
    # next_line = file.readline()
    content = file.read()
    # print(lines)
    # print(next_line)
    print(content)

data in the file Updated content: data in the file


In [10]:
lines = ["Hello\n", "World\n"]
with open("output.txt", "w") as file:
    file.writelines(lines)

In [11]:
with open("data.txt", "r") as file:
    for line in file: print(line)

data in the file 

Updated content: data in the file


In [29]:
import numpy as np

In [30]:
a = np.array([-1, 1]) 
b = np.array([1, 1]) 
np.dot(a, b)

np.int64(0)

In [32]:
c = np.dot(a.T, b)
c

np.int64(0)

In [34]:
X=np.array([[1,0,1],[2,2,2]]) 
X.ndim

2

In [41]:
X=np.array([[1,0],[0,1]]) 
Y=np.array([[2,2],[2,2]]) 
Z=np.dot(X,Y)
Z

array([[2, 2],
       [2, 2]])

In [36]:
with open("data.txt", "r") as file:
    FileContent=file.readline() 
    print(FileContent)

data in the file 



In [37]:
with open("Example.txt","w") as writefile: 
    writefile.write("This is line A\n") 
    writefile.write("This is line B\n")


In [38]:
with open("Example.txt","a") as file1: 
    file1.write("This is an additional line\n")

In [39]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]
out

array([1, 2])

In [42]:
with open("Example1.txt","r") as file1: 
    FileContent=file1.readlines() 
    print(FileContent)

['This is line 1 \n', 'This is line 2\n', 'This is line 3']


In [58]:
import requests
from bs4 import BeautifulSoup

# Specify the URL of the webpage you want to scrape
url = 'https://en.wikipedia.org/wiki/IBM'

# Send an HTTP GET request to the webpage
response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0'})

# Store the HTML content in a variable
html_content = response.text

# Create a BeautifulSoup object to parse the HTML
soup = BeautifulSoup(html_content, 'html.parser')

# Display a snippet of the HTML content
print(html_content[:500])

# Find all <a> tags (anchor tags) in the HTML
links = soup.find_all('a')
# Iterate through the list of links and print their text
for link in links:
    print(link.text)

<!DOCTYPE html>
<html class="client-nojs vector-feature-language-in-header-enabled vector-feature-language-in-main-page-header-disabled vector-feature-page-tools-pinned-disabled vector-feature-toc-pinned-clientpref-1 vector-feature-main-menu-pinned-disabled vector-feature-limited-width-clientpref-1 vector-feature-limited-width-content-enabled vector-feature-custom-font-size-clientpref-1 vector-feature-appearance-pinned-clientpref-1 vector-feature-night-mode-enabled skin-theme-clientpref-day vect
Jump to content
Main page
Contents
Current events
Random article
About Wikipedia
Contact us
Help
Learn to edit
Community portal
Recent changes
Upload file
Special pages








Search

Donate
Create account
Log in
Donate
 Create account
 Log in
learn more
Contributions
Talk

(Top)



1
History




1.1
1910s–1950s




1.2
1960s–1980s




1.3
1990s–2000s




1.4
2010s–present




2
Corporate affairs




2.1
Business trends




2.2
Board and shareholders




2.3
Headquarters and offices




3
Prod

In [ ]:
import pandas as pd
URL = 'https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)'
tables = pd.read_html(URL)
df = tables[2] # the required table will have index 2
print(df)

In [67]:
def add(a):
    for i in range(1, 5):
        if i != 1:
            print(i)
add(2)

2
3
4


In [65]:
for i in range(1, 5):
    if 1 != 1:
        print(i)

In [74]:
class Rectangle(object): 

    def __init__(self,width=2,height =3,color='r'):

        self.height=height 

        self.width=width 

        self.color=color 

    def drawRectangle(self): 

        import matplotlib.pyplot as plt 

        plt.gca().add_patch(plt.Rectangle((0, 0),self.width, self.height ,fc=self.color)) 

        plt.axis('scaled') 
        plt.show()
        
rect=Rectangle()


In [75]:
a=np.array([0,1,0,1,0]) 

b=np.array([1,0,1,0,1]) 

a*b 

array([0, 0, 0, 0, 0])

In [76]:
a=np.array([1,1,1,1,1]) 

a+1

array([2, 2, 2, 2, 2])